const ACTION_NAMES = {
    ADD_TODO : 'ADD_TODO',
    DELETE_TODO : 'DELETE_TODO',
    DELETE_SELECTED_TODOS : 'DELETE_SELECTED_TODOS',
    MARK_AS_DONE : 'MARK_AS_DONE' 
}

export default ACTION_NAMES